version: "3.9"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map the dev server port
    volumes:
      - .:/app # Sync local files to the container
    environment:
      - CHOKIDAR_USEPOLLING=true # Required for hot reloading
    command: ["npm", "run", "dev"] # Use the development server
